global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-informatica-secureatsource
  regions:
    - ap-northeast-1
#   - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
#  small:
#    parameter_input: small.json
#    template_file: informatica-secureatsource-master.template
  medium:
    parameter_input: medium.json
    template_file: informatica-secureatsource-master.template
#  large:
#    parameter_input: large.json
#    template_file: informatica-secureatsource-master.template
